### PR TITLE
Xmi reader #9

### PR DESCRIPTION
**Pull request by egrygorova**
completed the task, also updated some README's from other components.
please review it.

### CODE REVIEW

**Comment by fmatthies** [comment]
The task is not done yet. Please make sure that every artifact from the former naming convention is updated. For instance (and this one should've thrown an error in eclipse?) in
`/src/main/java/de/julielab/jcore/reader/xmi/XmiCollectionReader.java` the package name is `de.julielab.jules...`

**Comment by fmatthies** [comment]
Likewise in the descriptor:
`<implementationName>de.julielab.jules.reader.XmiCollectionReader</implementationName>`

**Comment by egrygorova** [comment]
ok, I think I did it

**Comment by fmatthies** [comment]
Please refrain from changing/updating things that thematically don't belong to the task (issue) at hand.
E.g. updating readme's in this issue-branch that have nothing to do with the issue.
It makes it harder for me to get an overview and to review your changes! Just create new branches for conceptual changes that belong together.
Thanks :)

P.S.: I changed your changes to the Gazetteer Readme! The Gazetteer in `jcore-base` has no uniform descriptor for everything as it's dependent on the task one wants to perform.

**Comment by egrygorova** [comment]
ok, I will consider this next time

**Pull request merged**
