### PR TITLE
Corrected descriptor path and added plugin in POM for correct JUnit t…

### PR DESCRIPTION
**Pull request by phsieg**
…ests during build process.

Additionally, corrected version of the BioLemmatizer to parent version again since fork's branch 'integrateBioLemmatizer' had not the latest changes from base fork!

### CODE REVIEW

**Comment by khituras** [comment]
The description says that the POM was updated but the PR does not contain any changes to the POM...?

**Comment by phsieg** [comment]
Sorry, at first I didn't commit correctly so I did a second commit!

**Comment by khituras** [comment]
I just saw that the new plugin defines some rather strange looking properties. I don't think we need those, please remove the settings that we don't need.

**Comment by phsieg** [comment]
I removed the settings and checked the functionality of the new POM locally before committing.

**Comment by khituras** [comment]
LGTM; merged

**Pull request merged**
